services:
    app:
        build:
            dockerfile: ./docker/web/Dockerfile
        volumes:
            - ./LibraManager:/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        container_name: vue-app
        ports:
            - ${VUE_APP_HOST}:80

